CREATE DATABASE IF NOT EXISTS test_sass;
CREATE DATABASE IF NOT EXISTS sass;
CREATE USER 'admin'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON test_sass.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON sass.* TO 'admin'@'%';