"""changed session id to uuid type instead of int type

Revision ID: 03512d574586
Revises: b6da66ea6c17
Create Date: 2024-08-14 15:45:10.801000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03512d574586'
down_revision: Union[str, None] = 'b6da66ea6c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'session_id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=45),
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=45),
               existing_nullable=False)
    op.create_foreign_key(None, 'chat_sessions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.String(length=45),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('chat_messages', 'session_id',
               existing_type=sa.String(length=45),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
