"""changed column type to type in table accounts

Revision ID: 2d9d24f408ea
Revises: bb6fae706595
Create Date: 2024-08-12 16:15:43.824013

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "2d9d24f408ea"
down_revision: Union[str, None] = "bb6fae706595"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("type", sa.String(length=45), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "type")
    # ### end Alembic commands ###
