"""implemented polymorphic child relationships to chat_messenger table

Revision ID: 6e08d412e60e
Revises: 75c0c15bdc63
Create Date: 2024-08-13 13:09:43.056337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e08d412e60e'
down_revision: Union[str, None] = '75c0c15bdc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat_messenger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['chat_messenger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chat_messenger', sa.Column('type', sa.String(length=45), nullable=False))
    op.drop_column('chat_messenger', 'user_agent')
    op.drop_column('chat_messenger', 'ip_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messenger', sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=False))
    op.add_column('chat_messenger', sa.Column('user_agent', mysql.VARCHAR(length=45), nullable=False))
    op.drop_column('chat_messenger', 'type')
    op.drop_table('chat_user')
    op.drop_table('chat_agent')
    # ### end Alembic commands ###
