"""added chat_id to chat_messages table

Revision ID: 75c0c15bdc63
Revises: 2d9d24f408ea
Create Date: 2024-08-13 12:23:17.515393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "75c0c15bdc63"
down_revision: Union[str, None] = "2d9d24f408ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_messages", sa.Column("chat_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "chat_id")
    # ### end Alembic commands ###
