"""added foreign key back to chat messages that references chat session

Revision ID: adf5b5c442c4
Revises: 03512d574586
Create Date: 2024-08-14 15:48:24.182594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adf5b5c442c4"
down_revision: Union[str, None] = "03512d574586"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "chat_messages", "chat_sessions", ["session_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    # ### end Alembic commands ###
