"""updated chat logic

Revision ID: b6da66ea6c17
Revises: 6e08d412e60e
Create Date: 2024-08-13 21:01:04.862941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b6da66ea6c17'
down_revision: Union[str, None] = '6e08d412e60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'type',
               existing_type=mysql.VARCHAR(length=45),
               nullable=False)
    op.drop_column('chat_messages', 'chat_id')
    op.add_column('chat_sessions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.alter_column('chat_sessions', 'end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('chat_sessions_ibfk_1', 'chat_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'accounts', ['account_id'], ['id'])
    op.drop_column('chat_sessions', 'business_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('business_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.create_foreign_key('chat_sessions_ibfk_1', 'chat_sessions', 'business', ['business_id'], ['id'])
    op.alter_column('chat_sessions', 'end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('chat_sessions', 'account_id')
    op.add_column('chat_messages', sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('accounts', 'type',
               existing_type=mysql.VARCHAR(length=45),
               nullable=True)
    # ### end Alembic commands ###
