"""changed chat_messages table name to chat_logs

Revision ID: c67ead2939f5
Revises: 0143969b6f0a
Create Date: 2024-08-31 22:47:46.962959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c67ead2939f5"
down_revision: Union[str, None] = "0143969b6f0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_logs",
        sa.Column("session_id", sa.String(length=45), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_logs")
    # ### end Alembic commands ###
