"""changed column in users to account_type_id

Revision ID: cc0d25455300
Revises: be4372df1bd7
Create Date: 2024-08-11 11:45:56.104210

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "cc0d25455300"
down_revision: Union[str, None] = "be4372df1bd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("account_type_id", sa.Integer(), nullable=False))
    op.drop_constraint("users_ibfk_2", "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "account_types", ["account_type_id"], ["id"])
    op.drop_column("users", "account_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("account_type", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        "users_ibfk_2", "users", "account_types", ["account_type"], ["id"]
    )
    op.drop_column("users", "account_type_id")
    # ### end Alembic commands ###
