"""initialize tables



Revision ID: fbb318f6ebb9
Revises:
Create Date: 2024-09-22 10:08:03.017290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbb318f6ebb9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotel_rooms", sa.Column("guest_count_numeric", sa.Integer(), nullable=True)
    )
    op.add_column("hotel_rooms", sa.Column("price_numeric", sa.Float(), nullable=True))
    op.add_column(
        "hotel_rooms", sa.Column("tax_and_fee_numeric", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotel_rooms", "tax_and_fee_numeric")
    op.drop_column("hotel_rooms", "price_numeric")
    op.drop_column("hotel_rooms", "guest_count_numeric")
    # ### end Alembic commands ###
