"""made some columns not optional

Revision ID: 0143969b6f0a
Revises: 3d25162bed70
Create Date: 2024-08-30 21:43:33.650862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0143969b6f0a"
down_revision: Union[str, None] = "3d25162bed70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "chat_sessions", "account_id", existing_type=mysql.INTEGER(), nullable=False
    )
    op.alter_column(
        "chat_sessions", "end_time", existing_type=mysql.DATETIME(), nullable=False
    )
    op.alter_column(
        "facility", "account_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "facility", "account_id", existing_type=mysql.INTEGER(), nullable=True
    )
    op.alter_column(
        "chat_sessions", "end_time", existing_type=mysql.DATETIME(), nullable=True
    )
    op.alter_column(
        "chat_sessions", "account_id", existing_type=mysql.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
