"""got rid of messenger table and added extra request data to the session table

Revision ID: 3d25162bed70
Revises: f6c3fc51214d
Create Date: 2024-08-30 19:13:58.825980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3d25162bed70"
down_revision: Union[str, None] = "f6c3fc51214d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chat_messages_ibfk_1", "chat_messages", type_="foreignkey")
    op.drop_column("chat_messages", "messenger_id")
    op.add_column(
        "chat_sessions", sa.Column("ip_address", sa.String(length=45), nullable=False)
    )
    op.add_column(
        "chat_sessions", sa.Column("user_agent", sa.String(length=45), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_sessions", "user_agent")
    op.drop_column("chat_sessions", "ip_address")
    op.add_column(
        "chat_messages",
        sa.Column("messenger_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "chat_messages_ibfk_1",
        "chat_messages",
        "chat_messenger",
        ["messenger_id"],
        ["id"],
    )
    # ### end Alembic commands ###
