"""increased email max length

Revision ID: 4000efe2b054
Revises: cf0f9cc53fd3
Create Date: 2024-09-02 16:54:09.025002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4000efe2b054"
down_revision: Union[str, None] = "cf0f9cc53fd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "business",
        "email",
        existing_type=mysql.VARCHAR(length=45),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=mysql.VARCHAR(length=45),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=45),
        existing_nullable=False,
    )
    op.alter_column(
        "business",
        "email",
        existing_type=sa.String(length=100),
        type_=mysql.VARCHAR(length=45),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
