"""create hotel tables

Revision ID: 82e7c2a15862
Revises:
Create Date: 2024-09-15 23:16:06.473035

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "82e7c2a15862"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotels",
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("image_link", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("amenities", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_guest_reviews",
        sa.Column("date", sa.String(length=500), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("positive", sa.String(length=500), nullable=True),
        sa.Column("negative", sa.String(length=500), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_house_rules",
        sa.Column("check_in", sa.String(length=1000), nullable=True),
        sa.Column("check_out", sa.String(length=1000), nullable=True),
        sa.Column("cancellation_payment", sa.String(length=1000), nullable=True),
        sa.Column("children_beds", sa.String(length=1000), nullable=True),
        sa.Column("age_restriction", sa.String(length=1000), nullable=True),
        sa.Column("pets", sa.String(length=1000), nullable=True),
        sa.Column("groups", sa.String(length=1000), nullable=True),
        sa.Column("cards_accepted", sa.String(length=1000), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_location",
        sa.Column("city", sa.String(length=500), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_review",
        sa.Column("rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("staff_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("facilities_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("cleanliness_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("comfort_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("value_for_money_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("location_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("free_wifi_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("num_of_reviews", sa.Integer(), nullable=True),
        sa.Column("subjective_rating", sa.String(length=500), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_rooms",
        sa.Column("room_type", sa.JSON(), nullable=True),
        sa.Column("guest_count", sa.String(length=500), nullable=True),
        sa.Column("price", sa.JSON(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hotel_rooms")
    op.drop_table("hotel_review")
    op.drop_table("hotel_location")
    op.drop_table("hotel_house_rules")
    op.drop_table("hotel_guest_reviews")
    op.drop_table("hotels")
    # ### end Alembic commands ###
