"""initialize tables

Revision ID: b9b4536ba29f
Revises:
Create Date: 2024-09-19 08:41:22.465915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9b4536ba29f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("type", sa.String(length=45), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_categories",
        sa.Column("name", sa.String(length=45), nullable=False),
        sa.Column("keywords", sa.String(length=45), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotels",
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("image_link", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amenities", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "business",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=45), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=45), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=False),
        sa.Column("user_agent", sa.String(length=45), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "facility",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=10000), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_guest_reviews",
        sa.Column("date", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("positive", sa.Text(), nullable=True),
        sa.Column("negative", sa.Text(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_house_rules",
        sa.Column("check_in", sa.Text(), nullable=True),
        sa.Column("check_out", sa.Text(), nullable=True),
        sa.Column("cancellation_payment", sa.Text(), nullable=True),
        sa.Column("children_beds", sa.Text(), nullable=True),
        sa.Column("age_restriction", sa.Text(), nullable=True),
        sa.Column("pets", sa.Text(), nullable=True),
        sa.Column("groups", sa.Text(), nullable=True),
        sa.Column("refundable_damage_deposit", sa.Text(), nullable=True),
        sa.Column("smoking", sa.Text(), nullable=True),
        sa.Column("cards_accepted", sa.Text(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_location",
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_review",
        sa.Column("rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("staff_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("facilities_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("cleanliness_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("comfort_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("value_for_money_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("location_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("free_wifi_rating_out_of_10", sa.Float(), nullable=True),
        sa.Column("num_of_reviews", sa.Integer(), nullable=True),
        sa.Column("subjective_rating", sa.Text(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hotel_rooms",
        sa.Column("room_type", sa.JSON(), nullable=True),
        sa.Column("guest_count", sa.JSON(), nullable=True),
        sa.Column("price", sa.JSON(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "business_data",
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("keywords", sa.String(length=45), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["data_categories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "business_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("password", sa.String(length=500), nullable=False),
        sa.Column("business_id", sa.Integer(), nullable=False),
        sa.Column("role_name", sa.String(length=45), nullable=False),
        sa.ForeignKeyConstraint(["business_id"], ["business.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "chat_logs",
        sa.Column("session_id", sa.String(length=45), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["chat_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_logs")
    op.drop_table("business_users")
    op.drop_table("business_data")
    op.drop_table("users")
    op.drop_table("hotel_rooms")
    op.drop_table("hotel_review")
    op.drop_table("hotel_location")
    op.drop_table("hotel_house_rules")
    op.drop_table("hotel_guest_reviews")
    op.drop_table("facility")
    op.drop_table("chat_sessions")
    op.drop_table("business")
    op.drop_table("hotels")
    op.drop_table("data_categories")
    op.drop_table("accounts")
    # ### end Alembic commands ###
