"""added ondelete foreign key constraints to the tables

Revision ID: cf0f9cc53fd3
Revises: c67ead2939f5
Create Date: 2024-09-01 09:27:49.404390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf0f9cc53fd3"
down_revision: Union[str, None] = "c67ead2939f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("business_ibfk_1", "business", type_="foreignkey")
    op.create_foreign_key(
        None, "business", "accounts", ["id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("business_data_ibfk_2", "business_data", type_="foreignkey")
    op.drop_constraint("business_data_ibfk_1", "business_data", type_="foreignkey")
    op.create_foreign_key(
        None,
        "business_data",
        "data_categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "business_data", "business", ["business_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("business_users_ibfk_1", "business_users", type_="foreignkey")
    op.drop_constraint("business_users_ibfk_2", "business_users", type_="foreignkey")
    op.create_foreign_key(
        None, "business_users", "accounts", ["id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "business_users", "business", ["business_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("chat_logs_ibfk_1", "chat_logs", type_="foreignkey")
    op.create_foreign_key(
        None, "chat_logs", "chat_sessions", ["session_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("chat_sessions_ibfk_1", "chat_sessions", type_="foreignkey")
    op.create_foreign_key(
        None, "chat_sessions", "accounts", ["account_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("facility_ibfk_1", "facility", type_="foreignkey")
    op.create_foreign_key(
        None, "facility", "accounts", ["account_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("users_ibfk_1", "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "accounts", ["id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key("users_ibfk_1", "users", "accounts", ["id"], ["id"])
    op.drop_constraint(None, "facility", type_="foreignkey")
    op.create_foreign_key(
        "facility_ibfk_1", "facility", "accounts", ["account_id"], ["id"]
    )
    op.drop_constraint(None, "chat_sessions", type_="foreignkey")
    op.create_foreign_key(
        "chat_sessions_ibfk_1", "chat_sessions", "accounts", ["account_id"], ["id"]
    )
    op.drop_constraint(None, "chat_logs", type_="foreignkey")
    op.create_foreign_key(
        "chat_logs_ibfk_1", "chat_logs", "chat_sessions", ["session_id"], ["id"]
    )
    op.drop_constraint(None, "business_users", type_="foreignkey")
    op.drop_constraint(None, "business_users", type_="foreignkey")
    op.create_foreign_key(
        "business_users_ibfk_2", "business_users", "business", ["business_id"], ["id"]
    )
    op.create_foreign_key(
        "business_users_ibfk_1", "business_users", "accounts", ["id"], ["id"]
    )
    op.drop_constraint(None, "business_data", type_="foreignkey")
    op.drop_constraint(None, "business_data", type_="foreignkey")
    op.create_foreign_key(
        "business_data_ibfk_1", "business_data", "business", ["business_id"], ["id"]
    )
    op.create_foreign_key(
        "business_data_ibfk_2",
        "business_data",
        "data_categories",
        ["category_id"],
        ["id"],
    )
    op.drop_constraint(None, "business", type_="foreignkey")
    op.create_foreign_key("business_ibfk_1", "business", "accounts", ["id"], ["id"])
    # ### end Alembic commands ###
