"""added more columns to hotel house rules table

Revision ID: fd86f3ffa820
Revises: ca02e590be64
Create Date: 2024-09-16 18:09:11.456939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd86f3ffa820"
down_revision: Union[str, None] = "ca02e590be64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hotel_house_rules",
        sa.Column("refundable_damage_deposit", sa.Text(), nullable=True),
    )
    op.add_column("hotel_house_rules", sa.Column("smoking", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hotel_house_rules", "smoking")
    op.drop_column("hotel_house_rules", "refundable_damage_deposit")
    # ### end Alembic commands ###
