"""added ondelete foreign constraint to hotel tables

Revision ID: 0db3c2997183
Revises: fbb318f6ebb9
Create Date: 2024-09-23 15:15:04.604847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0db3c2997183"
down_revision: Union[str, None] = "fbb318f6ebb9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "hotel_guest_reviews_ibfk_1", "hotel_guest_reviews", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "hotel_guest_reviews", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "hotel_house_rules_ibfk_1", "hotel_house_rules", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "hotel_house_rules", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("hotel_location_ibfk_1", "hotel_location", type_="foreignkey")
    op.create_foreign_key(
        None, "hotel_location", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("hotel_review_ibfk_1", "hotel_review", type_="foreignkey")
    op.create_foreign_key(
        None, "hotel_review", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("hotel_rooms_ibfk_1", "hotel_rooms", type_="foreignkey")
    op.create_foreign_key(
        None, "hotel_rooms", "hotels", ["hotel_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "hotel_rooms", type_="foreignkey")
    op.create_foreign_key(
        "hotel_rooms_ibfk_1", "hotel_rooms", "hotels", ["hotel_id"], ["id"]
    )
    op.drop_constraint(None, "hotel_review", type_="foreignkey")
    op.create_foreign_key(
        "hotel_review_ibfk_1", "hotel_review", "hotels", ["hotel_id"], ["id"]
    )
    op.drop_constraint(None, "hotel_location", type_="foreignkey")
    op.create_foreign_key(
        "hotel_location_ibfk_1", "hotel_location", "hotels", ["hotel_id"], ["id"]
    )
    op.drop_constraint(None, "hotel_house_rules", type_="foreignkey")
    op.create_foreign_key(
        "hotel_house_rules_ibfk_1", "hotel_house_rules", "hotels", ["hotel_id"], ["id"]
    )
    op.drop_constraint(None, "hotel_guest_reviews", type_="foreignkey")
    op.create_foreign_key(
        "hotel_guest_reviews_ibfk_1",
        "hotel_guest_reviews",
        "hotels",
        ["hotel_id"],
        ["id"],
    )
    # ### end Alembic commands ###
