async def fetch_hotel_data():
    return [
        {
            "id": 10,
            "title": "Super 8 by Wyndham Blackwell",
            "image_link": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/132424954.jpg?k=312f450a173bfec7438d9076375d3b27e34c1080cb4c137b1717ee3e1c1dffc8&o=&hp=1",
            "description": "Super 8 by Wyndham Blackwell has a fitness center, shared lounge and BBQ area in Blackwell. Featuring free bikes, the 2-star hotel has air-conditioned rooms with free WiFi, each with a private bathroom.\n\nAll rooms at the hotel come with a seating area and a flat-screen TV with satellite channels. At Super 8 by Wyndham Blackwell the rooms come with bed linen and towels.\n\nStaff at the accommodation are available to give information at the 24-hour front desk.\n\nThe nearest airport is Stillwater Regional Airport, 62 miles from Super 8 by Wyndham Blackwell.",
            "amenities": [
                "Fitness",
                "Clothes rack",
                "Hairdryer",
                "Fitness center",
                "Bathtub or shower",
                "Laundry",
                "Air conditioning",
                "Bowling",
                "Sitting area",
                "Telephone",
                "Fire extinguishers",
                "Toilet",
                "Vending machine (snacks)",
                "Express check-in/out",
                "Vending machine (drinks)",
                "Private check-in/out",
                "Lowered sink",
                "Additional charge",
                "Security alarm",
                "Private Bathroom",
                "English",
                "Shower",
                "Dining table",
                "Designated smoking area",
                "Invoice provided",
                "Bicycle rental",
                "BBQ facilities",
                "Bathroom emergency cord",
                "Free toiletries",
                "Upper floors accessible by stairs only",
                "Off-site",
                "Toilet with grab rails",
                "Linens",
                "Heating",
                "Key card access",
                "Alarm clock",
                "Bathtub",
                "CCTV outside property",
                "Daily housekeeping",
                "Wheelchair accessible",
                "Raised toilet",
                "Guest bathroom",
                "Facilities for disabled guests",
                "Towels",
                "Flat-screen TV",
                "Microwave",
                "Tea/Coffee maker",
                "Satellite channels",
                "Golf course (within 2 miles)",
                "24-hour front desk",
                "CCTV in common areas",
                "TV",
                "Fax/Photocopying",
                "Shared lounge/TV area",
                "Carpeted",
                "Smoke alarms",
                "Wake-up service/Alarm clock",
                "Non-smoking rooms",
                "Toilet paper",
                "Wake-up service",
                "Refrigerator",
            ],
            "hotel_review": {
                "id": 10,
                "rating_out_of_10": 5.8,
                "staff_rating_out_of_10": 7.9,
                "facilities_rating_out_of_10": 6,
                "cleanliness_rating_out_of_10": 6.6,
                "comfort_rating_out_of_10": 6.7,
                "value_for_money_rating_out_of_10": 7.2,
                "location_rating_out_of_10": 7.4,
                "free_wifi_rating_out_of_10": 6.3,
                "num_of_reviews": 147,
                "subjective_rating": "Rated okay",
                "hotel_id": 10,
            },
            "hotel_rooms": [
                {
                    "id": 89,
                    "room_type": [
                        "Queen Room - Smoking",
                        "1 queen bed",
                        "200 feet²",
                        "Air conditioning",
                        "Private Bathroom",
                        "Flat-screen TV",
                        "Coffee machine",
                        "Free Wifi",
                        "Free toiletries",
                        "Toilet",
                        "Bathtub or shower",
                        "Towels",
                        "Linens",
                        "Sitting area",
                        "TV",
                        "Refrigerator",
                        "Telephone",
                        "Satellite channels",
                        "Tea/Coffee maker",
                        "Microwave",
                        "Heating",
                        "Hairdryer",
                        "Guest bathroom",
                        "Wake-up service/Alarm clock",
                        "Carpeted",
                        "Cable channels",
                        "Wake-up service",
                        "Alarm clock",
                        "Wireless internet",
                        "Dining table",
                        "Upper floors accessible by stairs only",
                        "Clothes rack",
                        "Toilet paper",
                        "Hand sanitizer",
                        "More",
                        "Less",
                    ],
                    "guest_count": ["Max. people: 2"],
                    "price": ["$58", "Price", "$58", "+$11 taxes and fees"],
                    "guest_count_numeric": 2,
                    "price_numeric": 58,
                    "tax_and_fee_numeric": 11,
                    "hotel_id": 10,
                },
                {
                    "id": 90,
                    "room_type": [
                        "Queen Room - Smoking",
                        "1 queen bed",
                        "Free crib available on request",
                        "200 feet²Air conditioningPrivate BathroomFlat-screen TVCoffee machineFree Wifi",
                        "Free toiletries",
                        "Toilet",
                        "Bathtub or shower",
                        "Towels",
                        "Linens",
                        "Sitting area",
                        "TV",
                        "Refrigerator",
                        "Telephone",
                        "Satellite channels",
                        "Tea/Coffee maker",
                        "Microwave",
                        "Heating",
                        "Hairdryer",
                        "Guest bathroom",
                        "Wake-up service/Alarm clock",
                        "Carpeted",
                        "Cable channels",
                        "Wake-up service",
                        "Alarm clock",
                        "Wireless internet",
                        "Dining table",
                        "Upper floors accessible by stairs only",
                        "Clothes rack",
                        "Toilet paper",
                        "Hand sanitizer",
                    ],
                    "guest_count": ["Max. people: 2"],
                    "price": [
                        "$64",
                        "Price",
                        "$64",
                        "+$12 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "guest_count_numeric": 2,
                    "price_numeric": 64,
                    "tax_and_fee_numeric": 12,
                    "hotel_id": 10,
                },
                {
                    "id": 91,
                    "room_type": [
                        "Queen Room - Non-Smoking",
                        "1 queen bed",
                        "Free crib available on request",
                        "200 feet²Air conditioningPrivate BathroomFlat-screen TVFree Wifi",
                        "Free toiletries",
                        "Toilet",
                        "Bathtub or shower",
                        "Towels",
                        "Linens",
                        "Desk",
                        "Sitting area",
                        "TV",
                        "Refrigerator",
                        "Telephone",
                        "Satellite channels",
                        "Tea/Coffee maker",
                        "Microwave",
                        "Heating",
                        "Hairdryer",
                        "Guest bathroom",
                        "Wake-up service/Alarm clock",
                        "Carpeted",
                        "Wake-up service",
                        "Alarm clock",
                        "Dining table",
                        "Upper floors accessible by stairs only",
                        "Clothes rack",
                        "Toilet paper",
                        "Hand sanitizer",
                        "More",
                    ],
                    "guest_count": ["Max. people: 2"],
                    "price": [
                        "$64",
                        "Price",
                        "$64",
                        "+$12 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "guest_count_numeric": 2,
                    "price_numeric": 64,
                    "tax_and_fee_numeric": 12,
                    "hotel_id": 10,
                },
                {
                    "id": 92,
                    "room_type": [
                        "Queen Room with Two Queen Beds - Non-Smoking",
                        "2 queen beds",
                        "Free crib available on request",
                        "200 feet²Air conditioningPrivate BathroomFlat-screen TVFree Wifi",
                        "Free toiletries",
                        "Toilet",
                        "Bathtub or shower",
                        "Towels",
                        "Linens",
                        "Sitting area",
                        "TV",
                        "Refrigerator",
                        "Telephone",
                        "Satellite channels",
                        "Tea/Coffee maker",
                        "Microwave",
                        "Heating",
                        "Hairdryer",
                        "Guest bathroom",
                        "Wake-up service/Alarm clock",
                        "Carpeted",
                        "Cable channels",
                        "Wake-up service",
                        "Alarm clock",
                        "Wireless internet",
                        "Dining table",
                        "Upper floors accessible by stairs only",
                        "Clothes rack",
                        "Toilet paper",
                        "Hand sanitizer",
                        "More",
                    ],
                    "guest_count": ["Max. people: 2"],
                    "price": [
                        "$69",
                        "Price",
                        "$69",
                        "+$13 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "guest_count_numeric": 2,
                    "price_numeric": 69,
                    "tax_and_fee_numeric": 13,
                    "hotel_id": 10,
                },
                {
                    "id": 93,
                    "room_type": ["Max. people: 3"],
                    "guest_count": [
                        "$79",
                        "Price",
                        "$79",
                        "+$15 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "price": [
                        "Breakfast included in the price",
                        "•",
                        "Non-refundable",
                        "•",
                        "Pay in advance",
                        "discount may be available",
                    ],
                    "guest_count_numeric": None,
                    "price_numeric": None,
                    "tax_and_fee_numeric": None,
                    "hotel_id": 10,
                },
                {
                    "id": 94,
                    "room_type": ["Max. people: 4"],
                    "guest_count": [
                        "$89",
                        "Price",
                        "$89",
                        "+$17 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "price": [
                        "Breakfast included in the price",
                        "•",
                        "Non-refundable",
                        "•",
                        "Pay in advance",
                        "discount may be available",
                    ],
                    "guest_count_numeric": None,
                    "price_numeric": None,
                    "tax_and_fee_numeric": None,
                    "hotel_id": 10,
                },
                {
                    "id": 95,
                    "room_type": [
                        "Queen Room with Two Queen Beds - Smoking",
                        "Only 4 rooms left on our site",
                        "2 queen beds",
                        "Free crib available on request",
                        "200 feet²Air conditioningPrivate BathroomFlat-screen TVFree Wifi",
                        "Free toiletries",
                        "Toilet",
                        "Bathtub or shower",
                        "Towels",
                        "Linens",
                        "Sitting area",
                        "TV",
                        "Refrigerator",
                        "Telephone",
                        "Satellite channels",
                        "Tea/Coffee maker",
                        "Microwave",
                        "Heating",
                        "Hairdryer",
                        "Guest bathroom",
                        "Wake-up service/Alarm clock",
                        "Carpeted",
                        "Cable channels",
                        "Wake-up service",
                        "Alarm clock",
                        "Wireless internet",
                        "Dining table",
                        "Entire unit located on ground floor",
                        "Upper floors accessible by stairs only",
                        "Clothes rack",
                        "Toilet paper",
                        "Entire unit wheelchair accessible",
                        "Hand sanitizer",
                        "More",
                    ],
                    "guest_count": ["Max. people: 2"],
                    "price": [
                        "$69",
                        "Price",
                        "$69",
                        "+$13 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "guest_count_numeric": 2,
                    "price_numeric": 69,
                    "tax_and_fee_numeric": 13,
                    "hotel_id": 10,
                },
                {
                    "id": 96,
                    "room_type": ["Max. people: 3"],
                    "guest_count": [
                        "$79",
                        "Price",
                        "$79",
                        "+$15 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "price": [
                        "Breakfast included in the price",
                        "•",
                        "Non-refundable",
                        "•",
                        "Pay in advance",
                        "discount may be available",
                    ],
                    "guest_count_numeric": None,
                    "price_numeric": None,
                    "tax_and_fee_numeric": None,
                    "hotel_id": 10,
                },
                {
                    "id": 97,
                    "room_type": ["Max. people: 4"],
                    "guest_count": [
                        "$89",
                        "Price",
                        "$89",
                        "+$17 taxes and fees",
                        "Included:",
                        "Breakfast",
                        "Excluded:",
                        "18.75 % TAX",
                    ],
                    "price": [
                        "Breakfast included in the price",
                        "•",
                        "Non-refundable",
                        "•",
                        "Pay in advance",
                        "discount may be available",
                    ],
                    "guest_count_numeric": None,
                    "price_numeric": None,
                    "tax_and_fee_numeric": None,
                    "hotel_id": 10,
                },
            ],
            "hotel_house_rules": {
                "id": 10,
                "check_in": "From 14:00Guests are required to show a photo ID and credit card at check-in.",
                "check_out": "Until 11:00",
                "cancellation_payment": "Cancelation and prepayment policies vary according to accommodation type. Check what conditions apply to each option when making your selection.",
                "children_beds": "Child policiesChildren of all ages are welcome.Children 18 and above will be charged as adults at this property.To see correct prices and occupancy info, add the number and ages of children in your group to your search.Crib and extra bed policies0 - 2 yearsExtra bed upon request$10 per child, per nightCrib upon requestFree3+ yearsExtra bed upon request$10 per person, per nightPrices for cribs and extra beds aren't included in the total price. They'll have to be paid for separately during your stay.The number of extra beds and cribs allowed depends on the option you choose. Check your selected option for more info.All cribs and extra beds are subject to availability.",
                "age_restriction": "The minimum age for check-in is 18",
                "pets": "Pets are allowed. Charges may apply.",
                "groups": "When booking more than 9 rooms, different policies and additional fees may apply.",
                "refundable_damage_deposit": None,
                "smoking": None,
                "cards_accepted": " ",
                "hotel_id": 10,
            },
            "hotel_location": {
                "id": 10,
                "city": "Newkirk",
                "address": "\n1014 West Doolin Avenue, Blackwell, OK 74631, United States\n",
                "hotel_id": 10,
            },
            "hotel_guest_reviews": [
                {
                    "id": 86,
                    "date": "Reviewed: November 13, 2023",
                    "title": "It was very relaxing!",
                    "positive": "We enjoyed everything that we experienced there.",
                    "negative": None,
                    "hotel_id": 10,
                },
                {
                    "id": 87,
                    "date": "Reviewed: December 9, 2023",
                    "title": "Good",
                    "positive": "The staff was friendly and helpful.",
                    "negative": "The property was run down and poorly maintained. It smelled of cigarette smoke.",
                    "hotel_id": 10,
                },
                {
                    "id": 88,
                    "date": "Reviewed: July 17, 2024",
                    "title": "Slept good but hungry",
                    "positive": "Location",
                    "negative": "Breakfast was a single piece of toast. No yogurt or cereal or anything I expected at a Super 8. I was there at 8 am! No washer and dryer either.",
                    "hotel_id": 10,
                },
                {
                    "id": 89,
                    "date": "Reviewed: January 15, 2024",
                    "title": "Good",
                    "positive": "People",
                    "negative": "Age of building.",
                    "hotel_id": 10,
                },
                {
                    "id": 90,
                    "date": "Reviewed: July 24, 2023",
                    "title": "I'm not staying there again",
                    "positive": "The room stunk the odor was awful",
                    "negative": "The odor of the room",
                    "hotel_id": 10,
                },
                {
                    "id": 91,
                    "date": "Reviewed: June 8, 2023",
                    "title": "Good except the breakfast.",
                    "positive": "No breakfast, discount for local restaurant.",
                    "negative": "At least a continental breakfast for free.",
                    "hotel_id": 10,
                },
                {
                    "id": 92,
                    "date": "Reviewed: May 3, 2023",
                    "title": "Not as advertised.",
                    "positive": "Budget friendly.",
                    "negative": "Beer can left in fridge that had exploded. Had to change rooms. Second room stale food left in microwave. NO BREAKFAST unless you wish to upgrade the non existent breakfast to a buffet at $8 each in the local restaurant. I hate it when breakfast is advertised and is not available. TV remote did not work, kept freezing.",
                    "hotel_id": 10,
                },
                {
                    "id": 93,
                    "date": "Reviewed: March 15, 2023",
                    "title": "I've stayed at this location before, but it shows a lack of upkeep.",
                    "positive": "There was no breakfast, it was advertised as a free breakfast, but there was none.",
                    "negative": "There were things that needed attention.  The toilet need to be looked at, it took at least 10 minutes to fill, the bath tub had a soft spot in the floor and felt like it was going to break just standing in it.",
                    "hotel_id": 10,
                },
                {
                    "id": 94,
                    "date": "Reviewed: January 7, 2023",
                    "title": "Good",
                    "positive": "Good value and conveniently  located",
                    "negative": "No breakfast",
                    "hotel_id": 10,
                },
                {
                    "id": 95,
                    "date": "Reviewed: August 5, 2022",
                    "title": "Pleasant",
                    "positive": "clean, good price",
                    "negative": "no breakfast, no working ice machine",
                    "hotel_id": 10,
                },
            ],
        }
    ]
